=== GauriKanodia16/cat1-webdev/XSD_file.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Company">  
  <xs:complexType>  
  <xs:sequence> 
      <xs:element name="employee" maxOccurs="unbounded">  
      <xs:complexType>  
      <xs:sequence>  
          <xs:element name="name" type="xs:string"/>  
          <xs:element name="age" type="xs:integer"/> 
          <xs:element name="phone" type="xs:integer"/> 
          <xs:element name="salary" type="sal_res"/> 
          <xs:element name="designation" type="xs:string"/> 
          <xs:element name="email" type="xs:string"/>  
          <xs:element name="Emp_id" type="xs:string"/>
      </xs:sequence>  
      </xs:complexType>  
      </xs:element> 
  </xs:sequence>  
  </xs:complexType>  
  </xs:element> 

  <xs:simpleType  name = "sal_res">
      <xs:restriction base = "xs:decimal">
      <xs:minInclusive value = "50000"/>
      <xs:maxInclusive value = "200000"/>
      </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== GauriKanodia16/cat1-webdev/xml_file.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xslt-file.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="XSD_file.xsd">

    <employee>  
    <name>Jaswinder Pal Singh</name> 
    <age>59</age> 
    <phone>9415046999</phone>
    <salary>50000</salary>
    <designation>manager</designation>
    <email>pal.jassi@gmail.com</email> 
    <Emp_id>1101</Emp_id> 
    </employee> 
    
    
    <employee>  
    <name>Alok Nath</name> 
    <age>35</age> 
    <phone>9415046889</phone>
    <salary>150000</salary>
    <designation>Ass.manager</designation>
    <email>alok.nath@gmail.com</email> 
    <Emp_id>1102</Emp_id>  
    </employee> 

    
    <employee>  
    <name>Ishika Thapar</name> 
    <age>27</age> 
    <phone>9415046977</phone>
    <salary>80000</salary>
    <designation>HR</designation>
    <email>ishika.99@gmail.com</email>  
    <Emp_id>1103</Emp_id> 
    </employee> 


    <employee>  
    <name>Parminder singh ahuja</name> 
    <age>30</age> 
    <phone>9429046999</phone>
    <salary>65000</salary>
    <designation>manager</designation>
    <email>parminder.ahujai@gmail.com</email> 
    <Emp_id>1104</Emp_id> 

    </employee> 


    <employee>  
    <name>akansha rajput</name> 
    <age>25</age> 
    <phone>8319095499</phone>
    <salary>95000</salary>
    <designation>intern</designation>
    <email>akansha.rajput@gmail.com</email>
    <Emp_id>1105</Emp_id>   
    </employee>


</Company>
